variables:
  Solution: Rtti-plugin-x64.sln

image: registry.gitlab.com/colinsenner/docker-builds:latest

build:
  tags:
    - windows
  script:
  - echo building...
  - dir
  - echo CI_PROJECT_NAME = $CI_PROJECT_NAME
  - MsBuild.exe "%Solution%" -nologo -t:Build -p:Configuration=Release -p:Platform=x86
