variables:
  Solution: Rtti-plugin-x64.sln

build:
  tags:
    - windows
    - shared-windows
  script:
  - echo Building $CI_PROJECT_NAME...
  - dir
  - MsBuild.exe "%Solution%" -nologo -t:Build -p:Configuration=Release -p:Platform=x86
