variables:
  Solution: Rtti-plugin-x64.sln

build:
  tags:
    - windows
    - colin-pc
  script:
  - cmd.exe /k "`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat`" && powershell.exe -NoLogo -ExecutionPolicy Bypass -File ./build_vc2019.ps1"
  - set
  - dir
  - echo Done!
