variables:
  Solution: Rtti-plugin-x64.sln

build:
  tags:
    - windows
    - colin-pc
  before_script:
    - call "%VS160COMNTOOLS%\vsvars32" # import in path tools like msbuild, mstest, etc using VS script
  script:
    - |
      write-host "While it is true that I default to PowerShell, running cmd is easy..."
      set-content $env:public\inline.cmd -Value @'
      echo "This script is an inline script in .gitlab-ci.yml"
      echo "Running in project $env:CI_PROJECT_NAME with results at $env:CI_JOB_URL ($env:CI_JOB_URL)."
      echo "CMD / Windows version"
      ver
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
      echo VS160COMNTOOLS is "%VS160COMNTOOLS%"
      echo Building solution %Solution%...
      MsBuild.exe "%Solution%" -nologo -t:Build -p:Configuration=Release -p:Platform=x86
      '@

      CMD.EXE /C $env:public\inline.cmd
      exit $LASTEXITCODE
