variables:
  Solution: Rtti-plugin-x64.sln

build:
  tags:
    - windows
    - colin-pc
  script:
    - |
      write-host "While it is true that I default to PowerShell, running cmd is easy..."
      set-content $env:public\inline.cmd -Value @'
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"

      MsBuild.exe "%Solution%" -verbosity:minimal -nologo -t:Build -p:Configuration=Release -p:Platform=x86
      MsBuild.exe "%Solution%" -verbosity:minimal -nologo -t:Build -p:Configuration=Release -p:Platform=x64
      '@

      CMD.EXE /C $env:public\inline.cmd
      exit $LASTEXITCODE
