variables:
  Solution: Rtti-plugin-x64.sln

build:
  tags:
    - windows
    - colin-pc
  script:
    - |
      write-host "While it is true that I default to PowerShell, running cmd is easy..."
      set-content $env:public\inline.cmd -Value @'
      echo "This script is an inline script in .gitlab-ci.yml"
      echo "Running in project $env:CI_PROJECT_NAME with results at $env:CI_JOB_URL ($env:CI_JOB_URL)."
      echo "CMD / Windows version"
      ver
      echo "This artifact file was created by a CMD script" > myartifactfile.txt
      echo "Listing all Environment variables:"
      set
      '@

      CMD.EXE /C $env:public\inline.cmd
      exit $LASTEXITCODE
