variables:
  Solution: Rtti-plugin-x64.sln

build:
  tags:
    - windows
    - shared-windows
    - windows-1809
  script:
  - cmd.exe /k "`"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat`""
  - set
  - dir
  - echo Done!
