variables:
  Solution: Rtti-plugin-x64.sln

build:
  image: registry.gitlab.com/colinsenner/docker-builds:latest
  services:
    - docker:dind
  tags:
    - docker
  script:
  - echo building...
  - echo CI_PROJECT_NAME = $CI_PROJECT_NAME
  - MsBuild.exe "%Solution%" -nologo -t:Build -p:Configuration=Release -p:Platform=x86
