variables:
  Solution: Rtti-plugin-x64.sln

build:
  tags:
    - windows
    - colin-pc
  script:
    - cmd.exe /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
    - "Get-ChildItem -Path Env:"
    - ls
    - echo Done!
