variables:
  Solution: Rtti-plugin-x64.sln

build:
  tags:
    - windows
    - colin-pc
  script:
    - |
      ""C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\VsDevCmd.bat" && powershell.exe -NoLogo -ExecutionPolicy Bypass"
      echo Done!
